export enum VisualScriptingIpcChannelsMethodEnum {
    // ###> FILE_SYSTEM ###
    FILE_SYSTEM_LAST_OPENNED_DIR = "FILE_SYSTEM_LAST_OPENNED_DIR",
    FILE_SYSTEM_LIST = "FILE_SYSTEM_LIST",
    // ###< FILE_SYSTEM ###

    // ###> PROJECT ###
    PROJECT_CREATE = "PROJECT_CREATE",
    PROJECT_SAVE = "PROJECT_SAVE",
    PROJECT_LOAD = "PROJECT_LOAD",
    PROJECT_CLOSE = "PROJECT_CLOSE",
    PROJECT_NODES_LIST_OF = "PROJECT_NODES_LIST_OF",
    PROJECT_NODES_CREATE_DIRECTORY = "PROJECT_NODES_CREATE_DIRECTORY",
    PROJECT_NODES_CREATE_NODE = "PROJECT_NODES_CREATE_NODE",
    PROJECT_NODES_LOAD_NODE = "PROJECT_NODES_LOAD_NODE",
    // ###< PROJECT ###

    // ###> NODES ###

    // ###< NODES ###

    // ###> OPTIONS ###
    OPTIONS_GET_OPENTRACING = "OPTIONS_GET_OPENTRACING",
    // ###< OPTIONS ###
}
